package tokobangunan;

import java.awt.Toolkit;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import static tokobangunan.dashboard.btn_laporan;
import static tokobangunan.dashboard.lbl_status;
import static tokobangunan.dashboard.lbl_username;

/**
 * @author Aryaaazr_
 */
public class barang extends javax.swing.JFrame {
    
    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
        setLocationRelativeTo(this);
        tanggal();
        jam();
        loadTable();
        userSeasion();
        setIcon();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table_barang = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 20));

        photo_profile.setBackground(new java.awt.Color(255, 255, 255));
        photo_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account (2).png"))); // NOI18N
        photo_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(photo_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl_tanggal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 20));

        lbl_jam.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 80, 20));

        lbl_menu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_menu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_menu.setText("Menu");
        getContentPane().add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 20));

        txt_keterangan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txt_keterangan.setText("Master > Barang");
        getContentPane().add(txt_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        btn_master.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_master.setForeground(new java.awt.Color(255, 255, 255));
        btn_master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/monitor-removebg-preview (1).png"))); // NOI18N
        btn_master.setText("Master");
        btn_master.setBorderPainted(false);
        btn_master.setContentAreaFilled(false);
        btn_master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btn_dashboard.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1)_1.png"))); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        btn_transaksi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/purse-removebg-preview (1).png"))); // NOI18N
        btn_transaksi.setText("Transaksi");
        btn_transaksi.setBorderPainted(false);
        btn_transaksi.setContentAreaFilled(false);
        btn_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btn_pengaturan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/setting__1_-removebg-preview (1).png"))); // NOI18N
        btn_pengaturan.setText("Pengaturan");
        btn_pengaturan.setBorderPainted(false);
        btn_pengaturan.setContentAreaFilled(false);
        btn_pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        btn_logout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sign-out-option__1_-removebg-preview (1).png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 130, 40));

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 120, 30));

        table_barang.setBackground(new java.awt.Color(226, 216, 216));
        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Barang", "Kategori", "Nama Barang", "Brand", "Stock", "Harga Beli", "Harga Jual", "Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 510, 250));

        btn_refresh.setBackground(new java.awt.Color(21, 238, 56));
        btn_refresh.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh Data");
        btn_refresh.setBorderPainted(false);
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        btn_hapus.setBackground(new java.awt.Color(251, 30, 30));
        btn_hapus.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.setBorderPainted(false);
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        lbl_username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 250, 20));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Search :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 70, 30));

        btn_edit.setBackground(new java.awt.Color(255, 204, 0));
        btn_edit.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.setBorderPainted(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        btn_laporan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-removebg-preview (1).png"))); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masterActionPerformed
        this.setVisible(false);
        new master().setVisible(true);
    }//GEN-LAST:event_btn_masterActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengaturanActionPerformed
        this.setVisible(false);
        new pengaturan().setVisible(true);
    }//GEN-LAST:event_btn_pengaturanActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int logout = JOptionPane.showOptionDialog(this,
            "Anda yakin ingin Logout?", "Logout",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (logout == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Anda sudah logout, Silahkan login kembali.");
            this.setVisible(false);
            new login().setVisible(true);
        } else {
            this.setVisible(false);
            new dashboard().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        kosong();
        loadTable();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        loadTable();
    }//GEN-LAST:event_txt_cariKeyTyped

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // untuk mengahapus field table
        try {
            String sql = "DELETE FROM barang WHERE barang.nama_barang = '" + txt_cari.getText()+ "'";
            java.sql.Connection conn =(Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            int delete = JOptionPane.showOptionDialog(this,
            "Anda yakin ingin menghapus data?", "DELETE",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (delete == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void table_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_barangMouseClicked
        int baris = table_barang.rowAtPoint(evt.getPoint());
        String namaBarang = table_barang.getValueAt(baris, 2).toString();
        txt_cari.setText(namaBarang);
        if (table_barang.getValueAt(baris, 2) == null) {
            txt_cari.setText("");
        } else {
            txt_cari.setText(table_barang.getValueAt(baris, 2).toString());
        }
    }//GEN-LAST:event_table_barangMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        this.setVisible(false);
        new editDataBarang().setVisible(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        if (login.cb_status.getSelectedIndex()==0) {
            this.setVisible(false);
            new laporan().setVisible(true);
        } else {
            btn_laporan.setEnabled(false);
        }
    }//GEN-LAST:event_btn_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton btn_dashboard = new javax.swing.JButton();
    private javax.swing.JButton btn_edit;
    public static javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_laporan;
    public static final javax.swing.JButton btn_logout = new javax.swing.JButton();
    public static final javax.swing.JButton btn_master = new javax.swing.JButton();
    public static final javax.swing.JButton btn_pengaturan = new javax.swing.JButton();
    public static javax.swing.JButton btn_refresh;
    public static final javax.swing.JButton btn_transaksi = new javax.swing.JButton();
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public static final javax.swing.JLabel lbl_jam = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_menu = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_status = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_tanggal = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_username = new javax.swing.JLabel();
    public static final javax.swing.JLabel photo_profile = new javax.swing.JLabel();
    private javax.swing.JTable table_barang;
    public static final javax.swing.JTextField txt_cari = new javax.swing.JTextField();
    public static final javax.swing.JLabel txt_keterangan = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    private void tanggal() {
        java.util.Date tanggal = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
        String tanggall = dateFormat.format(tanggal);
        lbl_tanggal.setText(tanggall);
    }

    private void jam() {
        java.util.Date jam = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh.mm a");
        String jamm = dateFormat.format(jam);
        lbl_jam.setText(jamm);
    }

    private void loadTable() {
         String value = txt_cari.getText();
        // membuat tampilan table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Brand");
        model.addColumn("Stock");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Satuan");
        // memanggil data di SQL
        try {
            int no = 1;
            String SQL = "SELECT * FROM barang WHERE nama_barang like '%"+value+"%'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SQL);
            while (res.next()) {
                model.addRow(new Object[] {
                no++,res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                });    
            }
            table_barang.setModel(model);
        } catch (Exception e) {
        }
    } 
    
    private void userSeasion() {
        lbl_username.setText(login.txt_user.getText());
        lbl_status.setText((String) login.cb_status.getSelectedItem());
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }

    private void kosong() {
        txt_cari.setText(null);
    }
}