package tokobangunan;

import java.awt.Toolkit;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import static tokobangunan.barang.lbl_status;
//import static tokobangunan.barang.txt_cari;
////import static tokobangunan.dashboard.btn_laporan;
//import static tokobangunan.dashboard.lbl_username;
//import static tokobangunan.tambahDataPembeli.lbl_status;
//import static tokobangunan.tambahDataPembeli.txt_idPembeli;

/**
 *
 * @author Aryaaazr_
 */
public class editDataBarang extends javax.swing.JFrame {

    /**
     * Creates new form tambahDataBarang
     */
    public editDataBarang() {
        initComponents();
        setLocationRelativeTo(this);
        tanggal();
        jam();
        setIcon();
        kosong();
        comboBoxDatabase();
        userSeasion();
        loadTable();
        autoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo_profile = new javax.swing.JLabel();
        txt_keterangan = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_master = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_pengaturan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_tambahDataPembeli = new javax.swing.JLabel();
        lbl_garisHorizontal = new javax.swing.JLabel();
        lbl_idPembeli = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        lbl_noHP = new javax.swing.JLabel();
        txt_idBarang = new javax.swing.JTextField();
        txt_satuan = new javax.swing.JTextField();
        txt_namaBarang = new javax.swing.JTextField();
        lbl_noHP1 = new javax.swing.JLabel();
        lbl_noHP2 = new javax.swing.JLabel();
        lbl_noHP3 = new javax.swing.JLabel();
        lbl_noHP4 = new javax.swing.JLabel();
        txt_Brand = new javax.swing.JTextField();
        txt_hargaJual = new javax.swing.JTextField();
        txt_hargaBeli = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        lbl_tanggal = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        table_barang = new javax.swing.JTable();
        btn_laporan = new javax.swing.JButton();
        lbl_noHP5 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        lbl_noHP6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo_profile.setBackground(new java.awt.Color(255, 255, 255));
        photo_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account (2).png"))); // NOI18N
        photo_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(photo_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 20));

        txt_keterangan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txt_keterangan.setText("Master > Barang > Edit");
        getContentPane().add(txt_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        lbl_menu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_menu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_menu.setText("Menu");
        getContentPane().add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 20));

        btn_dashboard.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1)_1.png"))); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        btn_master.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_master.setForeground(new java.awt.Color(255, 255, 255));
        btn_master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/monitor-removebg-preview (1).png"))); // NOI18N
        btn_master.setText("Master");
        btn_master.setBorderPainted(false);
        btn_master.setContentAreaFilled(false);
        btn_master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btn_transaksi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/purse-removebg-preview (1).png"))); // NOI18N
        btn_transaksi.setText("Transaksi");
        btn_transaksi.setBorderPainted(false);
        btn_transaksi.setContentAreaFilled(false);
        btn_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btn_pengaturan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/setting__1_-removebg-preview (1).png"))); // NOI18N
        btn_pengaturan.setText("Pengaturan");
        btn_pengaturan.setBorderPainted(false);
        btn_pengaturan.setContentAreaFilled(false);
        btn_pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        btn_logout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sign-out-option__1_-removebg-preview (1).png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 130, 40));

        lbl_tambahDataPembeli.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_tambahDataPembeli.setText("Edit Data Barang");
        getContentPane().add(lbl_tambahDataPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 240, 30));

        lbl_garisHorizontal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(lbl_garisHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 168, 500, -1));

        lbl_idPembeli.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_idPembeli.setText("Id Barang");
        getContentPane().add(lbl_idPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, 20));

        lbl_alamat.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_alamat.setText("Nama Barang");
        getContentPane().add(lbl_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 20));

        lbl_noHP.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP.setText("Satuan");
        getContentPane().add(lbl_noHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, 20));
        getContentPane().add(txt_idBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 150, -1));
        getContentPane().add(txt_satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 150, -1));
        getContentPane().add(txt_namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, -1));

        lbl_noHP1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP1.setText("Brand");
        getContentPane().add(lbl_noHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 90, 20));

        lbl_noHP2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP2.setText("Stock");
        getContentPane().add(lbl_noHP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 90, 20));

        lbl_noHP3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP3.setText("Harga Beli");
        getContentPane().add(lbl_noHP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 90, 20));

        lbl_noHP4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP4.setText("Harga Jual");
        getContentPane().add(lbl_noHP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 90, 20));
        getContentPane().add(txt_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, -1));
        getContentPane().add(txt_hargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 150, -1));

        txt_hargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaBeliActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 150, -1));

        txt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockActionPerformed(evt);
            }
        });
        getContentPane().add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, -1));

        btn_clear.setBackground(new java.awt.Color(21, 238, 56));
        btn_clear.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.setBorderPainted(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 80, -1));

        lbl_tanggal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 20));

        lbl_jam.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 80, 20));

        lbl_username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 250, 20));

        cb_pilihKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Beton", "Logam", "Material", "Kayu", "Pasir", "Plastik", "Besi", "Peralatan", "Batu", "Genteng", "Aspal", "Semen" }));
        cb_pilihKategori.setToolTipText("");
        cb_pilihKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pilihKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, 20));

        btn_edit.setBackground(new java.awt.Color(255, 204, 0));
        btn_edit.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.setBorderPainted(false);
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 80, -1));

        table_barang.setBackground(new java.awt.Color(226, 216, 216));
        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Barang", "Nama Barang", "Kategori", "Brand", "Stock", "Harga Beli", "Harga Jual", "Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 510, 150));

        btn_laporan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-removebg-preview (1).png"))); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 150, 40));

        lbl_noHP5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP5.setText("Kategori");
        getContentPane().add(lbl_noHP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, 20));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 90, 30));

        lbl_noHP6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP6.setText("Search :");
        getContentPane().add(lbl_noHP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masterActionPerformed
        this.setVisible(false);
        new master().setVisible(true);
    }//GEN-LAST:event_btn_masterActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengaturanActionPerformed
        this.setVisible(false);
        new pengaturan().setVisible(true);
    }//GEN-LAST:event_btn_pengaturanActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int logout = JOptionPane.showOptionDialog(this,
            "Anda yakin ingin Logout?", "Logout",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (logout == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Anda sudah logout, Silahkan login kembali.");
            this.setVisible(false);
            new login().setVisible(true);
        } else {
            this.setVisible(false);
            new dashboard().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_hargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaBeliActionPerformed

    private void cb_pilihKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihKategoriActionPerformed
       comboBoxDatabase();
    }//GEN-LAST:event_cb_pilihKategoriActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            String sql = "UPDATE barang SET nama_barang = '"+txt_namaBarang.getText()+"', "
                    + "kategori ='"+cb_pilihKategori.getSelectedItem()+"', "
                    + "brand = '"+txt_Brand.getText()+"', "
                    + "stok='"+txt_stock.getText()+"', "
                    + "harga_beli = '"+txt_hargaBeli.getText()+"', "
                    + "harga_jual='"+txt_hargaJual.getText()+"', "
                    + "satuan = '"+txt_satuan.getText()+"' "
                    + "WHERE id_barang = '"+txt_idBarang.getText()+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadTable();
        kosong();
    }//GEN-LAST:event_btn_editActionPerformed

    private void table_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_barangMouseClicked
        // Menampilkan baris data ke dalam form pengisisan
        int baris = table_barang.rowAtPoint(evt.getPoint());
        String nim = table_barang.getValueAt(baris, 1).toString();
        txt_idBarang.setText(nim);
        txt_idBarang.disable();
        if (table_barang.getValueAt(baris, 2)==null) {
            txt_namaBarang.setText("");
        } else {
            txt_namaBarang.setText(table_barang.getValueAt(baris, 2).toString());
        }
        if (table_barang.getValueAt(baris, 3)==null) {
            cb_pilihKategori.setSelectedItem(this);
        } else {
            cb_pilihKategori.setSelectedItem(table_barang.getValueAt(baris, 3).toString());
        }
        if (table_barang.getValueAt(baris, 4)==null) {
            txt_Brand.setText("");
        } else {
            txt_Brand.setText(table_barang.getValueAt(baris, 4).toString());
        }
        if (table_barang.getValueAt(baris, 5)==null) {
            txt_stock.setText("");
        } else {
            txt_stock.setText(table_barang.getValueAt(baris, 5).toString());
        }
        if (table_barang.getValueAt(baris, 6)==null) {
            txt_hargaBeli.setText("");
        } else {
            txt_hargaBeli.setText(table_barang.getValueAt(baris, 6).toString());
        }
        if (table_barang.getValueAt(baris, 7)== null) {
            txt_hargaJual.setText("");
        } else {
            txt_hargaJual.setText(table_barang.getValueAt(baris, 7).toString());
        }
        if (table_barang.getValueAt(baris, 8)== null) {
            txt_satuan.setText("");
        } else {
            txt_satuan.setText(table_barang.getValueAt(baris, 8).toString());
        }
    }//GEN-LAST:event_table_barangMouseClicked

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        if (login.cb_status.getSelectedIndex()==0) {
            this.setVisible(false);
            new laporan().setVisible(true);
        } else {
            btn_laporan.setEnabled(false);
        }
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void txt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        loadTable();
    }//GEN-LAST:event_txt_cariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dashboard;
    public static javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_master;
    private javax.swing.JButton btn_pengaturan;
    private javax.swing.JButton btn_transaksi;
    public static final javax.swing.JComboBox<String> cb_pilihKategori = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_garisHorizontal;
    private javax.swing.JLabel lbl_idPembeli;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_noHP;
    private javax.swing.JLabel lbl_noHP1;
    private javax.swing.JLabel lbl_noHP2;
    private javax.swing.JLabel lbl_noHP3;
    private javax.swing.JLabel lbl_noHP4;
    private javax.swing.JLabel lbl_noHP5;
    private javax.swing.JLabel lbl_noHP6;
    public static final javax.swing.JLabel lbl_status = new javax.swing.JLabel();
    private javax.swing.JLabel lbl_tambahDataPembeli;
    private javax.swing.JLabel lbl_tanggal;
    public static final javax.swing.JLabel lbl_username = new javax.swing.JLabel();
    private javax.swing.JLabel photo_profile;
    private javax.swing.JTable table_barang;
    private javax.swing.JTextField txt_Brand;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_hargaBeli;
    private javax.swing.JTextField txt_hargaJual;
    private javax.swing.JTextField txt_idBarang;
    private javax.swing.JLabel txt_keterangan;
    private javax.swing.JTextField txt_namaBarang;
    private javax.swing.JTextField txt_satuan;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables

    private void tanggal() {
        java.util.Date tanggal = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMMMMMMM yyyy");
        String tanggall = dateFormat.format(tanggal);
        lbl_tanggal.setText(tanggall);
    }

    private void jam() {
        java.util.Date jam = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh.mm a");
        String jamm = dateFormat.format(jam);
        lbl_jam.setText(jamm);
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }

    private void kosong() {
        txt_idBarang.setText(null);
        txt_namaBarang.setText(null);
        cb_pilihKategori.setSelectedItem(this);
        txt_Brand.setText(null);
        txt_hargaBeli.setText(null);
        txt_hargaJual.setText(null);
        txt_stock.setText(null);
        txt_satuan.setText(null);
    }

    private void comboBoxDatabase() {
        try {
            String sql = "SELECT * FROM kategori";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                cb_pilihKategori.addItem(rs.getString("nama_kategori")); 
            }
            rs.last();
            int jumlahData = rs.getRow();
            rs.first();
        } catch (Exception e) {
        }
    }
    
    private void userSeasion() {
        lbl_username.setText(login.txt_user.getText());
        lbl_status.setText((String) login.cb_status.getSelectedItem());
    }
    
    private void loadTable() {
        String value = txt_cari.getText();
        // membuat tampilan table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Brand");
        model.addColumn("Stock");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Satuan");
        // memanggil data di SQL
        try {
            int no = 1;
            String SQL = "SELECT * FROM barang WHERE nama_barang like '%"+value+"%'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SQL);
            while (res.next()) {
                model.addRow(new Object[] {
                no++,res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                });    
            }
            table_barang.setModel(model);
        } catch (Exception e) {
        }
    } 
    
    public void autoID() {
        try {
            String sql = "SELECT * FROM barang ORDER BY id_barang DESC";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String idBarang = rs.getString("id_barang").substring(3);
                String id = "" + (Integer.parseInt(idBarang)+1);
                String angka = "";
                
                if (id.length()==1) {
                    angka = "0000";
                } else if (id.length()==2) {
                    angka = "000";
                } else if (id.length()==3){
                    angka = "00";
                } else if (id.length()==4) {
                    angka = "0";
                } else {
                    angka = "";
                }
                txt_idBarang.disable();
                txt_idBarang.setText("BRG" + angka + id);
            } else {
                txt_idBarang.setText("BRG00001");
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            System.out.println("autonumber");
        }
    }
}
