package tokobangunan;

import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
/**
 * @author Aryaaazr_
 */
public class login extends javax.swing.JFrame {
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(this); // untuk menempatkan ditengah ketika di run
        setIcon(); // untuk mengatur icon pada tampilan menu
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_user = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lbl_status = new javax.swing.JLabel();
        lbl_password1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_user.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lbl_user.setText("User");
        lbl_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 30, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 240, 200));

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 230, 30));

        btn_login.setBackground(new java.awt.Color(0, 51, 255));
        btn_login.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setBorderPainted(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 110, 30));

        btn_register.setBackground(new java.awt.Color(0, 51, 255));
        btn_register.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("REGISTER");
        btn_register.setBorderPainted(false);
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 110, 30));

        lbl_status.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lbl_status.setText("Pilih Status");
        lbl_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        lbl_password1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lbl_password1.setText("Password");
        lbl_password1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 230, 30));

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));
        getContentPane().add(cb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgorund login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        getAccessibleContext().setAccessibleDescription("Version 0.1");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        this.setVisible(false);
        new register().setVisible(true);
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        try {
            // untuk string sql pertama
            String sql = "SELECT * FROM akun WHERE user = '" +txt_user.getText() +"' AND password = '" +txt_password.getText() + "' AND status = '" + cb_status.getSelectedItem()+"'";
            // koneksi database
            java.sql.Connection conn = (Connection)config.configDB();
            // koneksi query sql pertama
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            // untuk OPTION LOGIN
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Anda berhasil login sebagai " + cb_status.getSelectedItem());
                this.setVisible(false);
                new dashboard().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Login gagal, Silahkan periksa kembali");
                txt_user.setText(null);
                txt_password.setText(null);
                cb_status.setSelectedItem(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        //        try {
            //            String sql = "SELECT user FROM akun WHERE user = '" +txt_user.getText() +"'";
            //            java.sql.Connection conn = (Connection)config.configDB();
            //            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            //            java.sql.ResultSet rs = pst.executeQuery();
            //            if (rs.next()) {
                //                dashboard.lbl_username.setText(rs.getString(1));
                //                new dashboard().setVisible(true);
                //            }
            //        } catch (Exception e) {
            //        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        login bg = new login();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_login;
    public static javax.swing.JButton btn_register;
    public static final javax.swing.JComboBox<String> cb_status = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_user;
    public static final javax.swing.JPasswordField txt_password = new javax.swing.JPasswordField();
    public static final javax.swing.JTextField txt_user = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }
}
