/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobangunan;

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
import java.awt.event.KeyEvent;
        
/**
 * @author Aryaaazr_
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setIcon();
        setLocationRelativeTo(this); // untuk menempatkan jframe berada di tengah
        autoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        lbl_pegawai = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_pilihStatus = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        txt_idPegawai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));
        combo_status.setToolTipText("");
        combo_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_status.setFocusable(false);
        getContentPane().add(combo_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, 30));

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, 30));

        btn_register.setBackground(new java.awt.Color(0, 51, 255));
        btn_register.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("REGISTER");
        btn_register.setBorderPainted(false);
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 100, 30));

        btn_batal.setBackground(new java.awt.Color(251, 30, 30));
        btn_batal.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.setBorderPainted(false);
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 30));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 230, 30));

        lbl_pegawai.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_pegawai.setText("ID Pegawai");
        lbl_pegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        lbl_password.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_password.setText("Password");
        lbl_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        lbl_pilihStatus.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_pilihStatus.setText("Pilih Status");
        lbl_pilihStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_pilihStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        lbl_user.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_user.setText("User");
        lbl_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        txt_idPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgorund login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        try {
            // untuk menyimpan data di table akun
            String sql = "INSERT INTO akun VALUES ('" + txt_user.getText() + "','" + txt_password.getText() + "','" + combo_status.getSelectedItem() + "')";
            // untuk menyimpan data di table pegawai
            String sqll = "INSERT INTO pegawai VALUES ( '"+txt_idPegawai.getText()+"', '"+""+"', '"+""+"', '"+""+"', '"+txt_user.getText()+"')";
            // untuk koneksi database
            java.sql.Connection conn = (Connection)config.configDB();
            // untuk statement string sql table akun
            java.sql.PreparedStatement st = conn.prepareStatement(sql);
            st.execute();
            // untuk statement string sql table pegawai
            java.sql.PreparedStatement stt = conn.prepareStatement(sqll);
            stt.execute();
            JOptionPane.showMessageDialog(this, "Selamat, Data anda sudah tersimpan");
            this.setVisible(false);
            new  login().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukkan data dengan benar!\n" + e.getMessage());
            this.setVisible(false);
            new register().setVisible(true);
        }
        kosong();
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        kosong();
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_idPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_register;
    public static final javax.swing.JComboBox<String> combo_status = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_pegawai;
    private javax.swing.JLabel lbl_pilihStatus;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_idPegawai;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void kosong() {
        txt_user.setText(null);
        txt_password.setText(null);
        combo_status.setSelectedItem(this);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }
    
    public void autoID() {
        try {
            String sql = "SELECT * FROM pegawai ORDER BY id_pegawai DESC";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String idPegawai = rs.getString("id_pegawai").substring(3);
                String id = "" + (Integer.parseInt(idPegawai)+1);
                String angka = "";
                
                if (id.length()==1) {
                    angka = "000";
                } else if (id.length()==2) {
                    angka = "00";
                } else if (id.length()==3){
                    angka = "0";
                } else {
                    angka = "";
                }
                txt_idPegawai.setText("PG" + "0" + angka + id);
            } else {
                txt_idPegawai.setText("PG0001");
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            System.out.println("autonumber");
        }
    }
}