/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobangunan;

import java.awt.Toolkit;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
//import static tokobangunan.barang.lbl_status;
//import static tokobangunan.barang.lbl_username;
////import static tokobangunan.dashboard.btn_laporan;
//import static tokobangunan.dashboard.lbl_username;
//import static tokobangunan.tambahDataBarang.cb_pilihKategori;
//import static tokobangunan.tambahDataPembeli.txt_alamat;
//import static tokobangunan.tambahDataPembeli.txt_idPembeli;
//import static tokobangunan.tambahDataPembeli.txt_namaPembeli;
//import static tokobangunan.tambahDataPembeli.txt_noHP;

/**
 *
 * @author Aryaaazr_
 */
public class tambahDataPegawai extends javax.swing.JFrame {

    /**
     * Creates new form tambahDataPegawai
     */
    public tambahDataPegawai() {
        initComponents();
        setLocationRelativeTo(this);
        tanggal();
        jam();
        setIcon();
        comboBoxDatabase();
        kosong();
        userSeasion();
        comboBoxDatabase1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_noHP = new javax.swing.JTextField();
        lbl_tanggal = new javax.swing.JLabel();
        lbl_idPegawai = new javax.swing.JLabel();
        txt_keterangan = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        lbl_jam = new javax.swing.JLabel();
        lbl_namaPegawai = new javax.swing.JLabel();
        photo_profile = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_pengaturan = new javax.swing.JButton();
        txt_alamat = new javax.swing.JTextField();
        lbl_noHP = new javax.swing.JLabel();
        lbl_garisHorizontal = new javax.swing.JLabel();
        lbl_tambahDataPembeli = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        lbl_alamat = new javax.swing.JLabel();
        txt_namaPegawai = new javax.swing.JTextField();
        lbl_menu = new javax.swing.JLabel();
        btn_master = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        cb_pilihUser = new javax.swing.JComboBox<>();
        btn_laporan = new javax.swing.JButton();
        cb_pilihIDPegawai = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_noHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, -1));

        lbl_tanggal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 20));

        lbl_idPegawai.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_idPegawai.setText("Id Pegawai");
        getContentPane().add(lbl_idPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, 20));

        txt_keterangan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txt_keterangan.setText("Master > Pegawai > Tambah Data");
        getContentPane().add(txt_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        btn_transaksi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/purse-removebg-preview (1).png"))); // NOI18N
        btn_transaksi.setText("Transaksi");
        btn_transaksi.setBorderPainted(false);
        btn_transaksi.setContentAreaFilled(false);
        btn_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        lbl_status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 20));

        btn_tambah.setBackground(new java.awt.Color(72, 90, 248));
        btn_tambah.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.setBorderPainted(false);
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 80, -1));

        lbl_jam.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 80, 20));

        lbl_namaPegawai.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_namaPegawai.setText("Nama Pegawai");
        getContentPane().add(lbl_namaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 90, 20));

        photo_profile.setBackground(new java.awt.Color(255, 255, 255));
        photo_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account (2).png"))); // NOI18N
        photo_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(photo_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_logout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sign-out-option__1_-removebg-preview (1).png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 130, 40));

        btn_pengaturan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_pengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/setting__1_-removebg-preview (1).png"))); // NOI18N
        btn_pengaturan.setText("Pengaturan");
        btn_pengaturan.setBorderPainted(false);
        btn_pengaturan.setContentAreaFilled(false);
        btn_pengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 200, -1));

        lbl_noHP.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_noHP.setText("No HP");
        getContentPane().add(lbl_noHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 20));

        lbl_garisHorizontal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(lbl_garisHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 168, 500, -1));

        lbl_tambahDataPembeli.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_tambahDataPembeli.setText("Tambah Data Pegawai");
        getContentPane().add(lbl_tambahDataPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, 30));

        btn_clear.setBackground(new java.awt.Color(21, 238, 56));
        btn_clear.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.setBorderPainted(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 80, -1));

        lbl_alamat.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lbl_alamat.setText("Alamat");
        getContentPane().add(lbl_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, 20));
        getContentPane().add(txt_namaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 200, -1));

        lbl_menu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_menu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_menu.setText("Menu");
        getContentPane().add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 20));

        btn_master.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_master.setForeground(new java.awt.Color(255, 255, 255));
        btn_master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/monitor-removebg-preview (1).png"))); // NOI18N
        btn_master.setText("Master");
        btn_master.setBorderPainted(false);
        btn_master.setContentAreaFilled(false);
        btn_master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btn_dashboard.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1)_1.png"))); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        lbl_username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 250, 20));

        cb_pilihUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===  Pilih User  ===" }));
        cb_pilihUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihUserActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pilihUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 200, 30));

        btn_laporan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-removebg-preview (1).png"))); // NOI18N
        btn_laporan.setText("Laporan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 150, 40));

        cb_pilihIDPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== Pilih ID Pegawai ===" }));
        getContentPane().add(cb_pilihIDPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 200, -1));

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background menu.jpg"))); // NOI18N
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int logout = JOptionPane.showOptionDialog(this,
            "Anda yakin ingin Logout?", "Logout",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (logout == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Anda sudah logout, Silahkan login kembali.");
            this.setVisible(false);
            new login().setVisible(true);
        } else {
            this.setVisible(false);
            new dashboard().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_pengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengaturanActionPerformed
        this.setVisible(false);
        new pengaturan().setVisible(true);
    }//GEN-LAST:event_btn_pengaturanActionPerformed

    private void btn_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masterActionPerformed
        this.setVisible(false);
        new master().setVisible(true);
    }//GEN-LAST:event_btn_masterActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        try {
            String sql = "UPDATE pegawai SET id_pegawai = '"+cb_pilihIDPegawai.getSelectedItem()+"',"
                    + "nama_pegawai = '"+txt_namaPegawai.getText()+"',"
                    + "alamat = '"+txt_alamat.getText()+"', "
                    + "no_telp = '"+txt_noHP.getText()+"'"
                    + "WHERE user = '"+cb_pilihUser.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            this.setVisible(false);
            new pegawai().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            this.setVisible(false);
            new tambahDataPegawai().setVisible(true);
        }
        kosong();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void cb_pilihUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihUserActionPerformed
        comboBoxDatabase();
    }//GEN-LAST:event_cb_pilihUserActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        if (login.cb_status.getSelectedIndex()==0) {
            this.setVisible(false);
            new laporan().setVisible(true);
        } else {
            btn_laporan.setEnabled(false);
        }
    }//GEN-LAST:event_btn_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahDataPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_master;
    private javax.swing.JButton btn_pengaturan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JComboBox<String> cb_pilihIDPegawai;
    private javax.swing.JComboBox<String> cb_pilihUser;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_garisHorizontal;
    private javax.swing.JLabel lbl_idPegawai;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_namaPegawai;
    private javax.swing.JLabel lbl_noHP;
    public static final javax.swing.JLabel lbl_status = new javax.swing.JLabel();
    private javax.swing.JLabel lbl_tambahDataPembeli;
    private javax.swing.JLabel lbl_tanggal;
    public static final javax.swing.JLabel lbl_username = new javax.swing.JLabel();
    private javax.swing.JLabel photo_profile;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JLabel txt_keterangan;
    private javax.swing.JTextField txt_namaPegawai;
    private javax.swing.JTextField txt_noHP;
    // End of variables declaration//GEN-END:variables

    private void tanggal() {
        java.util.Date tanggal = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMMMMMMM yyyy");
        String tanggall = dateFormat.format(tanggal);
        lbl_tanggal.setText(tanggall);
    }

    private void jam() {
        java.util.Date jam = new java.util.Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh.mm a");
        String jamm = dateFormat.format(jam);
        lbl_jam.setText(jamm);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }
    
    private void comboBoxDatabase() {
        try {
            String sql = "SELECT * FROM pegawai";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                cb_pilihUser.addItem(rs.getString("user")); 
            }
        } catch (Exception e) {
        }
    }
    
    private void comboBoxDatabase1() {
        try {
            String sql = "SELECT * FROM pegawai";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                cb_pilihIDPegawai.addItem(rs.getString("id_pegawai")); 
            }
        } catch (Exception e) {
        }
    }

    private void kosong() {
        cb_pilihUser.setSelectedItem(this);
        txt_namaPegawai.setText(null);
        txt_alamat.setText(null);
        txt_noHP.setText(null);
    }
    
    private void userSeasion() {
        lbl_username.setText(login.txt_user.getText());
        lbl_status.setText((String) login.cb_status.getSelectedItem());
    }
}
