/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobangunan;

import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aryaaazr_
 */
public class tambahBarang extends javax.swing.JFrame {

    /**
     * Creates new form tambahBarang
     */
    public tambahBarang() {
        initComponents();
        setLocationRelativeTo(this);
        kosong();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setIcon();
        autoIDBarang();
        loadTable();
        loadTableCari();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        table_barang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_pilih = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        txt_idBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_namaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_pilihKategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_hargaBeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_hargaJual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_input = new javax.swing.JButton();
        cb_satuan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Building");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Tambah Data Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_barang.setBackground(new java.awt.Color(226, 216, 216));
        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Barang", "Nama Barang", "Kategori", "Brand", "Stock", "Harga Beli", "Harga Jual", "Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_barang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_barang);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Search :");

        btn_pilih.setBackground(new java.awt.Color(72, 90, 248));
        btn_pilih.setForeground(new java.awt.Color(255, 255, 255));
        btn_pilih.setText("Pilih");
        btn_pilih.setBorderPainted(false);
        btn_pilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(204, 0, 0));
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("Batal");
        btn_batal.setBorderPainted(false);
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(153, 255, 0));
        btn_refresh.setText("Refresh");
        btn_refresh.setBorderPainted(false);
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        txt_idBarang.setEnabled(false);

        jLabel3.setText("ID Barang");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Kategori");

        cb_pilihKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aspal", "Baja", "Batu", "Beton", "Besi", "Cat", "Genteng", "Kayu", "Logam", "Material", "Pasir", "Plastik", "Peralatan", "Semen" }));

        jLabel6.setText("Brand");

        jLabel7.setText("Stock");

        jLabel8.setText("Harga Beli");

        jLabel9.setText("Harga Jual");

        jLabel10.setText("Satuan");

        btn_input.setBackground(new java.awt.Color(255, 255, 0));
        btn_input.setText("Input");
        btn_input.setBorderPainted(false);
        btn_input.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });

        cb_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batang", "Biji", "Box", "Buah", "Kg", "Pcs", "Pick Up" }));
        cb_satuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_pilihKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_idBarang)
                            .addComponent(txt_brand)
                            .addComponent(txt_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_stock)
                                    .addComponent(txt_hargaBeli)
                                    .addComponent(txt_hargaJual)
                                    .addComponent(cb_satuan, 0, 134, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_input)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pilih)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal)))
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_pilihKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cb_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_input)
                    .addComponent(btn_pilih)
                    .addComponent(btn_batal))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_barangMouseClicked
        // Menampilkan baris data ke dalam form pengisisan
        int baris = table_barang.rowAtPoint(evt.getPoint());
        String nim = table_barang.getValueAt(baris, 1).toString();
        txt_idBarang.setText(nim);
        txt_idBarang.disable();
        if (table_barang.getValueAt(baris, 2)==null) {
            txt_namaBarang.setText("");
        } else {
            txt_namaBarang.setText(table_barang.getValueAt(baris, 2).toString());
        }
        if (table_barang.getValueAt(baris, 3)==null) {
            cb_pilihKategori.setSelectedItem(this);
        } else {
            cb_pilihKategori.setSelectedItem(table_barang.getValueAt(baris, 3).toString());
        }
        if (table_barang.getValueAt(baris, 4)==null) {
            txt_brand.setText("");
        } else {
            txt_brand.setText(table_barang.getValueAt(baris, 4).toString());
        }
        if (table_barang.getValueAt(baris, 5)==null) {
            txt_stock.setText("");
        } else {
            txt_stock.setText(table_barang.getValueAt(baris, 5).toString());
        }
        if (table_barang.getValueAt(baris, 6)==null) {
            txt_hargaBeli.setText("");
        } else {
            txt_hargaBeli.setText(table_barang.getValueAt(baris, 6).toString());
        }
        if (table_barang.getValueAt(baris, 7)== null) {
            txt_hargaJual.setText("");
        } else {
            txt_hargaJual.setText(table_barang.getValueAt(baris, 7).toString());
        }
        if (table_barang.getValueAt(baris, 8)== null) {
            cb_satuan.setSelectedItem("");
        } else {
            cb_satuan.setSelectedItem(table_barang.getValueAt(baris, 8).toString());
        }
    }//GEN-LAST:event_table_barangMouseClicked

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        int i = table_barang.getSelectedRow();

        String id = table_barang.getValueAt(i, 1).toString();
        String harga = table_barang.getValueAt(i, 6).toString();

        pembelian.txt_IDbarang.setText(id);
        pembelian.txt_harga.setText(harga);

        dispose();
    }//GEN-LAST:event_btn_pilihActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        loadTableCari();
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        loadTableCari();
    }//GEN-LAST:event_txt_cariKeyTyped

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        loadTable();
        kosong();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        try {
            String sql = "INSERT INTO barang VALUES ('"+txt_idBarang.getText()+"','"
                    +txt_namaBarang.getText()+"','"+cb_pilihKategori.getSelectedItem()+"','"
                    +txt_brand.getText()+"','"+txt_stock.getText()+"','"
                    +txt_hargaBeli.getText()+"','"+txt_hargaJual.getText()+"','"
                    +cb_satuan.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
    }//GEN-LAST:event_btn_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahBarang().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cb_pilihKategori;
    private javax.swing.JComboBox<String> cb_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    private javax.swing.JTable table_barang;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_hargaBeli;
    private javax.swing.JTextField txt_hargaJual;
    private javax.swing.JTextField txt_idBarang;
    private javax.swing.JTextField txt_namaBarang;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
    
    private void loadTable() {
        // membuat tampilan table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Brand");
        model.addColumn("Stock");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Satuan");
        // memanggil data di SQL
        try {
            int no = 1;
            String SQL = "SELECT * FROM barang ";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SQL);
            while (res.next()) {
                model.addRow(new Object[] {
                no++,res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                });    
            }
            table_barang.setModel(model);
        } catch (Exception e) {
        }
    }
    
    private void loadTableCari() {
        String value = txt_cari.getText();
            // membuat tampilan table
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Id Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Kategori");
        model.addColumn("Brand");
        model.addColumn("Stock");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Satuan");
        // memanggil data di SQL
        try {
            int no = 1;
            String SQL = "SELECT * FROM barang WHERE nama_barang like '%"+value+"%'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(SQL);
            while (res.next()) {
                model.addRow(new Object[] {
                no++,res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                });    
            }
            table_barang.setModel(model);
        } catch (Exception e) {
        }
    }
    
    private void kosong() {
        txt_cari.setText(null);
        txt_namaBarang.setText(null);
        cb_pilihKategori.setSelectedItem(null);
        txt_brand.setText(null);
        txt_stock.setText(null);
        txt_hargaBeli.setText(null);
        txt_hargaJual.setText(null);
        cb_satuan.setSelectedItem(null);
        autoIDBarang();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpeg")));
    }
    
    private void autoIDBarang() {
        try {
            String sql = "SELECT * FROM barang ORDER BY id_barang DESC";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String idBarang = rs.getString("id_barang").substring(3);
                String id = "" + (Integer.parseInt(idBarang)+1);
                String angka = "";
                
                if (id.length()==1) {
                    angka = "0000";
                } else if (id.length()==2) {
                    angka = "000";
                } else if (id.length()==3){
                    angka = "00";
                } else if (id.length()==4) {
                    angka = "0";
                } else {
                    angka = "";
                }
                txt_idBarang.disable();
                txt_idBarang.setText("BRG" + angka + id);
            } else {
                txt_idBarang.setText("BRG00001");
            }
            rs.close();
            pst.close();
        } catch (Exception e) {
            System.out.println("autonumber");
        }
    }
}